### ISSUE TITLE
babel v6

### ISSUE THREAD

**Issue by shorif2000** [jciccio/react-js-banner#11]
if i have babel in my webpack the one in this repo interferes

after webpack and you try to load in browser., it will error with 

SCRIPT5022: only one instance of babel-polyfill is allowed

**Comment by jciccio** [comment]
Working on it

**Comment by jciccio** [comment]
Added in v4, also removed unused ones making the overall package smaller

**Comment by jciccio** [comment]
Also removed Polyfill in v0.5.2
