### ISSUE TITLE
transitionAppearTime transitionTime seem to have no effect

### ISSUE THREAD

**Issue by nathanhere** [jciccio/react-js-banner#18]
Thanks for your work! It totally works for my use case, so this is not at all a "deal breaker," moreso just a nice-to-have--**transitionAppearTime** **transitionTime** seem to have no effect. Using in conjunction with Semantic UI React (0.88.1), Semantic UI CSS (2.4.1), React-beautiful-dnd (13.0.0), React (16.9.0), and latest Chrome Browser. Let me know if you'd like any additional info.

**Comment by jciccio** [comment]
Cool, will try to take a look at it, will let you know! Can you maybe provide me a full example please?

**Comment by jciccio** [comment]
Hey, any chance you can provide me an example of thi @nathanhere ?

**Comment by nathanhere** [comment]
Hi @jciccio , apologies I haven't been able to get around to it yet--it's crunch time until after next week, would it be alright to provide the example then?

**Comment by jciccio** [comment]
Sure, no problem
