### ISSUE TITLE
html support

### ISSUE THREAD

**Issue by shorif2000** [jciccio/react-js-banner#9]
can you add html support through title props?

**Comment by jciccio** [comment]
Hi, you can do it by sending the props in the form:
[html here]

for instance: 

<Banner title={[<div>HTML <i> Italics</i></div>]} />

**Comment by shorif2000** [comment]
I think what i wanted to say as well is to have text only support as well?

**Comment by jciccio** [comment]
Do you mean like passing JSX through an arrow function? 

And passing just a plain text like "Hello world" and render it?

**Comment by jciccio** [comment]
Added support to pass a list of children, assume aside from the arrow func. for convenience it is what you asked:

Like being able to render by passing html as follows:

```
<Banner showBanner={true}>
  <div>
    <h1>h1</h1>
    <h2>h2</h2>
    <h3>h3</h3>
  </div>
</Banner>
```
